name: zaliczenie_flutter
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  word_generator: ^0.4.3
  google_fonts: ^4.0.4
  kumi_popup_window: ^2.0.0-nullsafety
  english_words: ^4.0.0
  provider: ^6.0.0
  page_transition: ^2.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Italic-VariableFont_wght.ttf
          weight: 300
  assets:
    - assets/